

export const RETRIEVE_NOWPLAYING_FOODS_SUCCESS = 'RETRIEVE_NOWPLAYING_FOODS_SUCCESS';
export const RETRIEVE_FOODS_SEARCH_RESULT_SUCCESS = 'RETRIEVE_FOODS_SEARCH_RESULT_SUCCESS';
export const RETRIEVE_CATEGORIES_SUCCESS = 'RETRIEVE_CATEGORIES_SUCCESS';
export const ADD_TO_CARDS_SUCCESS = 'ADD_TO_CARDS_SUCCESS';
